# Generated by Django 5.2.5 on 2025-09-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options_book_publication_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
